const questions = [
  {question:"What is the capital of France?", options:["Paris","Berlin","Madrid","Rome"], answer:"Paris"},
  {question:"Which language is used to style web pages?", options:["HTML","CSS","Python","Java"], answer:"CSS"},
  {question:"Who developed the theory of relativity?", options:["Newton","Einstein","Galileo","Tesla"], answer:"Einstein"},
  {question:"What is 9 × 8?", options:["72","81","64","69"], answer:"72"},
  {question:"Which planet is known as the Red Planet?", options:["Mars","Venus","Jupiter","Saturn"], answer:"Mars"},
  {question:"Who is the CEO of Tesla?", options:["Elon Musk","Jeff Bezos","Bill Gates","Mark Zuckerberg"], answer:"Elon Musk"},
  {question:"What is the largest ocean on Earth?", options:["Atlantic","Pacific","Indian","Arctic"], answer:"Pacific"},
  {question:"Which gas do plants absorb from the atmosphere?", options:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"], answer:"Carbon Dioxide"},
  {question:"What is the square root of 144?", options:["10","11","12","14"], answer:"12"},
  {question:"Which country hosted the 2016 Summer Olympics?", options:["China","Brazil","UK","Russia"], answer:"Brazil"},
  {question:"Which country is famous for the Great Wall?", options:["China","India","Japan","Korea"], answer:"China"},
  {question:"Who wrote 'Romeo and Juliet'?", options:["Shakespeare","Hemingway","Tolkien","Dickens"], answer:"Shakespeare"},
  {question:"Which element has the chemical symbol 'O'?", options:["Oxygen","Gold","Iron","Silver"], answer:"Oxygen"},
  {question:"Which continent is Egypt in?", options:["Africa","Asia","Europe","South America"], answer:"Africa"},
  {question:"Who painted the Mona Lisa?", options:["Leonardo da Vinci","Van Gogh","Picasso","Michelangelo"], answer:"Leonardo da Vinci"},
  {question:"What is the freezing point of water?", options:["0°C","32°C","100°C","-10°C"], answer:"0°C"},
  {question:"Which planet is the largest in the Solar System?", options:["Earth","Mars","Jupiter","Saturn"], answer:"Jupiter"},
  {question:"Which instrument measures atmospheric pressure?", options:["Barometer","Thermometer","Hygrometer","Altimeter"], answer:"Barometer"},
  {question:"Who invented the telephone?", options:["Alexander Graham Bell","Thomas Edison","Nikola Tesla","Guglielmo Marconi"], answer:"Alexander Graham Bell"},
  {question:"Which is the smallest prime number?", options:["0","1","2","3"], answer:"2"},
  {question:"Which gas is essential for breathing?", options:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"], answer:"Oxygen"},
  {question:"What is the tallest mountain in the world?", options:["K2","Everest","Kangchenjunga","Lhotse"], answer:"Everest"},
  {question:"What is 15 × 12?", options:["180","175","150","165"], answer:"180"},
  {question:"Which country is known as the Land of the Rising Sun?", options:["China","Japan","Thailand","India"], answer:"Japan"},
  {question:"What is H2O commonly known as?", options:["Water","Hydrogen Peroxide","Oxygen","Salt"], answer:"Water"},
  {question:"Who discovered penicillin?", options:["Alexander Fleming","Louis Pasteur","Marie Curie","Gregor Mendel"], answer:"Alexander Fleming"},
  {question:"Which planet is closest to the Sun?", options:["Earth","Mercury","Venus","Mars"], answer:"Mercury"},
  {question:"Which organ pumps blood throughout the body?", options:["Liver","Heart","Lungs","Kidneys"], answer:"Heart"},
  {question:"What is the largest mammal?", options:["Elephant","Blue Whale","Giraffe","Hippopotamus"], answer:"Blue Whale"},
  {question:"Which country gifted the Statue of Liberty to the USA?", options:["France","UK","Germany","Italy"], answer:"France"},
  {question:"Who is known as the Father of Computers?", options:["Charles Babbage","Alan Turing","Steve Jobs","Bill Gates"], answer:"Charles Babbage"},
  {question:"Which metal has the chemical symbol 'Fe'?", options:["Iron","Gold","Silver","Copper"], answer:"Iron"},
  {question:"What is 100 ÷ 4?", options:["20","25","24","30"], answer:"25"},
  {question:"Which is the longest river in the world?", options:["Amazon","Nile","Yangtze","Mississippi"], answer:"Nile"},
  {question:"Which is the primary language of Brazil?", options:["Portuguese","Spanish","French","English"], answer:"Portuguese"},
  {question:"Who wrote 'Harry Potter' series?", options:["J.K. Rowling","J.R.R. Tolkien","Stephen King","C.S. Lewis"], answer:"J.K. Rowling"},
  {question:"Which vitamin is produced when sunlight hits the skin?", options:["Vitamin A","Vitamin B12","Vitamin C","Vitamin D"], answer:"Vitamin D"},
  {question:"Which country is famous for sushi?", options:["China","Japan","Korea","Thailand"], answer:"Japan"},
  {question:"What is 7 × 7?", options:["42","49","56","36"], answer:"49"},
  {question:"Which organ is responsible for detoxifying chemicals?", options:["Liver","Kidney","Heart","Lungs"], answer:"Liver"},
  {question:"What is the hardest natural substance?", options:["Diamond","Gold","Iron","Platinum"], answer:"Diamond"},
  {question:"Which planet is known for its rings?", options:["Mars","Saturn","Jupiter","Uranus"], answer:"Saturn"},
  {question:"Who painted the Sistine Chapel ceiling?", options:["Michelangelo","Raphael","Leonardo","Donatello"], answer:"Michelangelo"},
  {question:"What is 20 + 45?", options:["55","65","70","75"], answer:"65"},
  {question:"Which country is home to kangaroos?", options:["New Zealand","Australia","South Africa","India"], answer:"Australia"},
  {question:"What is the boiling point of water?", options:["100°C","90°C","80°C","110°C"], answer:"100°C"},
  {question:"Who is the author of 'The Odyssey'?", options:["Homer","Plato","Aristotle","Socrates"], answer:"Homer"},
  {question:"Which gas do humans exhale?", options:["Oxygen","Carbon Dioxide","Nitrogen","Helium"], answer:"Carbon Dioxide"},
  {question:"What is 8 × 12?", options:["88","96","108","84"], answer:"96"},
  {question:"Which country has the Eiffel Tower?", options:["Italy","France","Germany","Spain"], answer:"France"},
  {question:"Who discovered gravity?", options:["Newton","Einstein","Galileo","Tesla"], answer:"Newton"},
  {question:"Which organelle is the powerhouse of the cell?", options:["Nucleus","Mitochondria","Ribosome","Chloroplast"], answer:"Mitochondria"},
  {question:"What is the chemical formula of table salt?", options:["NaCl","KCl","H2O","CO2"], answer:"NaCl"},
  {question:"Which is the largest desert in the world?", options:["Sahara","Gobi","Kalahari","Arctic"], answer:"Sahara"}
];
